# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - PROD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-az-app-service-dotnet:
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') || 
      (github.event_name == 'release' && github.event.release.target_commitish == 'main')
    uses: vestfoldfylke/shared/.github/workflows/deploy-az-app-service-dotnet.yml@main
    with:
      azure_appname: ${{ vars.AZURE_FUNCTIONAPP_NAME_PROD }} # required
      azure_functionapp_package_path: "postmottak-arkivering-dotnet" # required. set to path project path. if multiple projects exists in same solution, set this to the project to deploy
      dotnet_version: "10.0" # required and must follow the TargetFramework version set in the project file (*.csproj)
    secrets:
      azure_publishprofile: ${{ secrets.PROD_AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
